<table>
    <tr>
            <td>{$title_field}</td>
    </tr>
    <tr>
            <td>
              {$show_from_field}
            </td>
    </tr>
    <tr>
        <td>
            {$show_to_field}
        </td>
    </tr>
    <tr>
            <td>{$max_results_field}</td>
    </tr>
    <tr>
            <td>{$order_by_field}</td>
    </tr>
    <tr>
        <td>{$order_type_field}</td>
    </tr>
    <tr>
            <td>{$term_select_field}</td>
    </tr>
</table>